### PR TITLE
Fix a bunch of things.

### PR DESCRIPTION
**Pull request by techflashYT**
Read the individual commit descriptions to see what each of them do, the early ones were mostly me trying to get spaces in the links, as you can see I reversed the broken changes, then got that to work, and yes I viewed the entire thing on my fork to make sure nothing broke, everything is still fine.  ~~More commits still coming~~, I'm currently trying to update the images, feel free to give feedback if you don't like something (e.g. if one of the images came out wrong)

### CODE REVIEW

**Comment by techflashYT** [comment]
All done :D  enjoy all of that done for you.
Edit: If you want the raw video, gif, and pngs that I made for the updated images, just let me know, I'll add them in here in a "media" directory that you can look over.

**Comment by techflashYT** [comment]
OK, Really all done now, there was just a few extra things, and one extra commit just now because the one image broke.

**Comment by HerXayah** [comment]
Add urself yo Contributors and ill merge

**Comment by techflashYT** [comment]
> Add urself yo Contributors and ill merge

I did did I not?  Let me check.
Edit: Yeah, I did, I'm right there at the bottom.
image

**Pull request merged**
